# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flixter-og' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flixter-og
  pod "AlamofireImage"

  target 'flixter-ogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flixter-ogUITests' do
    # Pods for testing
  end

end
